stages:
  - build
  - package

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - node_modules/
    - gui/node_modules/

build-backend:
  stage: build
  image: node:13
  script:
    - npm install
    - npm run test

build-frontend:
  stage: build
  image: node:13
  script:
    - cd gui
    - npm install
    - ./node_modules/.bin/ng build

package-docker:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --build-arg SA_PASSWORD=$SA_PASSWORD --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE
