stages:
  - install
  - build
  - build
  - test

cache:
  paths:
  - node_modules/
  - disziplinen/
  - gui/

install:
  stage: install
  script:
    - git submodule update --init --recursive

build-backend:
  stage: build
  image: node:13
  script:
    - npm install

build-frontend:
  stage: build
  image: node:13
  script:
    - cd gui
    - npm install

test-backend:
  stage: test
  image: node:13
  script:
    - npm run test
