stages:
  - install
  - test

cache:
  paths:
  - node_modules/
  - disziplinen/

install:
  stage: install
  image: node:13
  script:
    - git submodule init
    - git submodule update
    - npm install

test:
  stage: test
  image: node:13
  script:
    - npm run test
