stages:
  - build
  - package

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - node_modules/
    - frontend/

build:
  stage: build
  image: node:13
  script:
    - npm install
    - npm run test
    - tar cJf dsc.tar.xz --exclude=dsc.tar.xz --exclude=./.git/ .
  artifacts:
    paths:
      - ./dsc.tar.xz

package-docker:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --build-arg SA_PASSWORD=$SA_PASSWORD --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE
