stages:
  - build
  - test

cache:
  paths:
  - node_modules/
  - disziplinen/

build:
  stage: build
  image: node:13
  script:
    - npm install
    - git submodule update --checkout --init

test:
  stage: test
  image: node:13
  script:
    - npm run test
