version: '3'
services:
  dsc:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - digital_shooting
  db:
    image: mongo:3.6-jessie
    ports:
      - "27017:27017"
    networks:
      - digital_shooting

networks:
  digital_shooting:
    driver: bridge
